[package]
name = "dram"
version = "0.1.0"
edition = "2021"
description = "A wee pour of Homebrew: fast bottle-only package installer for macOS"
license = "BSD-2-Clause"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
flate2 = "1"
futures = "0.3"
glob = "0.3"
hex = "0.4"
indicatif = "0.17"
regex = "1"
reqwest = { version = "0.12", features = ["json", "gzip", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tar = "0.4"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs", "sync"] }
toml = "0.8"
walkdir = "2"

[profile.release]
lto = "thin"
